### ISSUE TITLE
Doesn't work if you start from the pull request list page

### ISSUE THREAD

**Issue by carols10cents** [carols10cents/github-back-button#1]
Only works if i start from an individual pull request's page. I bet it's loading the pull request page with pjax too, so the removeClass isn't happening. Goddammit.

**Comment by noahm** [comment]
Add this in addition to your current one-liner for an easy fix:

``` js
$(window).on('pjax:end', function(e) {
  $(".js-pull-request-tab").removeClass("js-pull-request-tab");
});
```

**Comment by carols10cents** [comment]
Ahhh it works! it works!!! Thank you so much @noahm !!!!! <3 <3 <3
